mv raw/rock/Sopor_Aeternus_&_The_Ensemble_Of_Shadows_-_Dead_Souls.mp3 dataset/test/rock
mv raw/rock/Keith_Richards_-_Amnesia.mp3 dataset/test/rock
mv raw/rock/Chris_Cornell_-_Dead_Wishes.mp3 dataset/test/rock
mv raw/rock/Amorphis_-_The_Four_Wise_Ones.mp3 dataset/test/rock
mv raw/rock/Мара_-_Где-то_моя_любовь.mp3 dataset/test/rock
mv raw/rock/Shinedown_-_Asking_For_It.mp3 dataset/test/rock
mv raw/rock/cover.jpg dataset/test/rock
mv raw/rock/Green_Grey_-_Мама.mp3 dataset/test/rock
mv raw/rock/Rob_Thomas_-_Trust_You.mp3 dataset/test/rock
mv raw/rock/Queen_-_You_Don't_Fool_Me__2011_Remaster_.mp3 dataset/test/rock
mv raw/rock/Dave_Gahan,_The_Hollywood_Strings_-_All_of_This_and_Nothing.mp3 dataset/test/rock
mv raw/rock/Скрябін_-_Притулися.mp3 dataset/test/rock
mv raw/rock/Александр_Иванов_-_Московская_осень.mp3 dataset/test/rock
mv raw/rock/Grey_Lands_-_Lo-Fi_Junkie.mp3 dataset/test/rock
mv raw/rock/Adriano_Celentano_-_I_Love_You_Baby.mp3 dataset/test/rock
mv raw/rock/Кисельные_берега_-_Ещё_одна_минута_сна.mp3 dataset/test/rock
mv raw/rock/Shinedown_-_How_Did_You_Love.mp3 dataset/test/rock
mv raw/rock/Hollywood_Vampires_-_Raise_The_Dead.mp3 dataset/test/rock
mv raw/rock/Jeff_Buckley_-_Hallelujah.mp3 dataset/test/rock
mv raw/rock/Ленинград_-_Вип.mp3 dataset/test/rock
mv raw/rock/Сергей_Бабкин_-_Недотрога.mp3 dataset/test/rock
mv raw/rock/Ленинград_-_Красная_смородина.mp3 dataset/test/rock
mv raw/rock/Scorpions_-_The_Game_Of_Life.mp3 dataset/test/rock
mv raw/rock/Waste_Pipes_-_The_Deal.mp3 dataset/test/rock
mv raw/rock/Grey_Lands_-_False_Alarm.mp3 dataset/test/rock
mv raw/rock/Queen_-_Let_Me_Live__2011_Remaster_.mp3 dataset/test/rock
mv raw/rock/7Б_-_Осень.mp3 dataset/test/rock
mv raw/rock/Exxasens_-_Supernova.mp3 dataset/test/rock
mv raw/rock/Океан_Ельзи_-_Обійми__Обними_.mp3 dataset/test/rock
mv raw/rock/The_Rock_And_Rollers_-_Wear_My_Ring_Around_Your_Neck.mp3 dataset/test/rock
mv raw/rock/Elvis_Presley_-_Jailhouse_Rock__Remastered_Original_Version_.mp3 dataset/test/rock
mv raw/rock/Секрет_-_Ночь.mp3 dataset/test/rock
mv raw/rock/Keith_Richards_-_Heartstopper.mp3 dataset/test/rock
mv raw/rock/David_Gilmour_-_A_Boat_Lies_Waiting.mp3 dataset/test/rock
mv raw/rock/Бумбокс_-_Пєпєл.mp3 dataset/test/rock
mv raw/rock/Сплин_-_Сын.mp3 dataset/test/rock
mv raw/rock/Roxette_-_Wish_I_Could_Fly.mp3 dataset/test/rock
mv raw/rock/Ночные_Снайперы_-_Ты_город.mp3 dataset/test/rock
mv raw/rock/КняZz_-_Пассажир.mp3 dataset/test/rock
mv raw/rock/Atlantida_Project_-_Новое_Измерение.mp3 dataset/test/rock
