mv raw/hiphop/Geak_Show.mp3 dataset/test/hiphop
mv raw/hiphop/Dem_boyz.mp3 dataset/test/hiphop
mv raw/hiphop/Flame_Power_Moves.mp3 dataset/test/hiphop
mv raw/hiphop/Feel_me.mp3 dataset/test/hiphop
mv raw/hiphop/Gangsta_shit..mp3 dataset/test/hiphop
mv raw/hiphop/Dirty_lungs.mp3 dataset/test/hiphop
mv raw/hiphop/Dumb_On_Down.mp3 dataset/test/hiphop
mv raw/hiphop/Fresh.mp3 dataset/test/hiphop
mv raw/hiphop/Face_Down.mp3 dataset/test/hiphop
mv raw/hiphop/Drop_Girl.mp3 dataset/test/hiphop
mv raw/hiphop/Dont_love_you.mp3 dataset/test/hiphop
mv raw/hiphop/Fresh_Like_Me.mp3 dataset/test/hiphop
mv raw/hiphop/Gangsta's_Paradise.mp3 dataset/test/hiphop
mv raw/hiphop/Fuck_A_Hoe.mp3 dataset/test/hiphop
mv raw/hiphop/Don`t_Violate.mp3 dataset/test/hiphop
mv raw/hiphop/Everybody_know_me.mp3 dataset/test/hiphop
mv raw/hiphop/Gangsta.mp3 dataset/test/hiphop
mv raw/hiphop/Dont_Deserve_It.mp3 dataset/test/hiphop
mv raw/hiphop/Count_Me_In.mp3 dataset/test/hiphop
mv raw/hiphop/Dat_Lingo.mp3 dataset/test/hiphop
mv raw/hiphop/Genesis.mp3 dataset/test/hiphop
mv raw/hiphop/GBSB.mp3 dataset/test/hiphop
mv raw/hiphop/Doin'_What_I_Want.mp3 dataset/test/hiphop
mv raw/hiphop/Gangsta_shit.mp3 dataset/test/hiphop
mv raw/hiphop/From_the_darkness.mp3 dataset/test/hiphop
mv raw/hiphop/Gemme_Buck$.mp3 dataset/test/hiphop
mv raw/hiphop/Dumpin.mp3 dataset/test/hiphop
mv raw/hiphop/Do_It.mp3 dataset/test/hiphop
mv raw/hiphop/DJ_Crump.mp3 dataset/test/hiphop
mv raw/hiphop/Fight__crunk_remix_.mp3 dataset/test/hiphop
mv raw/hiphop/Drink.mp3 dataset/test/hiphop
mv raw/hiphop/Do_it_like_me_baby.mp3 dataset/test/hiphop
mv raw/hiphop/Duel_to_the_death.mp3 dataset/test/hiphop
mv raw/hiphop/Get_Loose.mp3 dataset/test/hiphop
mv raw/hiphop/Fall_back.mp3 dataset/test/hiphop
mv raw/hiphop/Dr._Phil.mp3 dataset/test/hiphop
mv raw/hiphop/Fed_x.mp3 dataset/test/hiphop
mv raw/hiphop/Everything_Bricksquad.mp3 dataset/test/hiphop
mv raw/hiphop/Elvis_Presley_BLVD.mp3 dataset/test/hiphop
mv raw/hiphop/Da_Jump_Off.mp3 dataset/test/hiphop
